[package]
name = "md-to-html"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
colored = "3.0.0"
markdown = "1.0.0-alpha.22"

[dev-dependencies]
tempfile = "3.17.1"
